In [2]:
import torch

在PyTorch中，torch.Tersor是存储和变换数据的主要工具。
tensor张量——多维数组

## 创建新tensor的方法
torch.empty  
torch.rand  
torch.zeros  
torch.tensor  
torch.new_ones  
torch.randn_like  

**可以通过shape或者size()来获取Tensor的形状**   
x.size()    
x.shape    

## Tensor的各种操作
以加法为例：  
1. y = torch.eand(5.3)   
print(x+y)  
2. torch.add(x+y)  
3. y.add_(x)  

## 索引(重要)
可以使用类似Numpy的索引操作来访问Tensor的一部分。
注意：索引出来的结果与源数据共享内存(修改一个，另一个一会改变)

## 改变形状
view是Pytorch中最常用的改变tensor形状的函数，但要求数据在内存中连续存储，且变形前后元素个数必须相同  
item()，可以将一个标量Tensor转换成一个Python number


## 广播机制
当两个形状不同的Tensor按元素运算时，可能会触发广播机制：先适当复制元素使这两个Tensor形状相同都再按元素运算。
例如：

In [3]:
x = torch.arange(1,3).view(1,2)
print(x)
y = torch.arange(1,4).view(3,1)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 其他
Tensor可以和numpy互相转换：
使用numpy()将Tensor转换成Numpy数组
使用from_numpy将Numpy数组转换成Tensor